(1000.htm)
{Основы игры|TerraBellica 2 правила игры|герои, колонизация, стратегия, дипломатия|Основы}
===
<p>TerraBellica 2 - многопользовательская онлайн стратегия, в которой все игроки развиваются и воюют на общей глобальной карте.
======
<p><b>Стратегия</b>

<p>Все юниты имеют дневной запас ходов, который можно расходовать как сразу, так и частями. В остальном же время в игре течет непрерывно: запас ходов юнитов, здоровье, мана магов плавно восстанавливаются в течение всего для, пока не достигают максимума. Все накладываемые магические заклинания имеют свою длительность; постройка зданий, добыча ресурсов - свою скорость. Жизнь в игре течет непрерывно.

<p>Сейчас в игре доступен мир Славия.

======
<p><a href=http://classic.localhost/worlds/1/0><b>Мортия</b></a>

<p>Славию населяют могучие альянсы и гордые одиночки, коварные монстры и неуловимые диверсанты. Множество колонистов прибывают в этот мир в надежде отвоевать у природы кусок земли и обрести здесь свой дом. Славия - непредсказуемый мир, притягивающая к себе новых полководцев, мечтающих обрести славу великих завоевателей; магов, жаждущих новых познаний и невиданной силы; торговцев, грезящих о сказочных прибылях; искателей приключений - всеми ими движет неведомая сила и предвкушение великих событий.

<p>Но Славия притянула не только людей... Силы тьмы во главе со своим повелителем - Темным Богом Креспом, вознамерились подчинить новую землю и ее обитателей. Бесчисленные орды голодных орков и разной нечисти проникли в этот светлый мир и наводнили его страхом и кровью... Теперь каждый новый колонист, вступующий на землю Славии, попадает под иго темного владыки и вынужден платить ему дань.

======Начало пути

<p><b>Начало пути</b>

<p>Каждый новичок получает в свое распоряжение героя в случайном месте, повозку с колонистами и небольшой багаж. Первоначальная задача - найти подходящее место для строительства первого замка (см. Замки).

<p>Злой дух Кресп окутывает первый замок игрока заклятием "Аура тьмы", которое создает защитный магический кокон вокруг города, непробиваемый для врагов. Кроме того, крестьяне, объятые страхом, начинают работать в 2 раза быстрее. Покровительство темного владыки позволит пройти первые шаги, не опасаясь быть уничтоженным со стороны развитого и сильного соседа. Поэтому главное внимание в начале игры стоит уделить развитию своего города.

<p>Но не думайте, что Кресп добр и хочет помочь вам... его цель - заставить вас больше работать, чтобы вы могли исправно наполнять его казну данью. Вначале дань будет совсем маленькой, и ее выплата не станет проблемой, но с каждым днем алчный повелитель будет требовать все больших выплат. И настанет время, когда дань станет более невыносимой, придет пора свергнуть ненавистное иго... и настанет час испытания, произойдет крещение огнем. И только сильный пройдет его с честью...
