{Мануал|Мануал|Руководство по развитию, основные вопросы|}
===
- Герой и первое поселение -

<br>Вы вошли в игру. Перед вами -- меню в левой части экрана. Справа сверх -- кнопка "В игру".
<br>Нажимаем.
<br>Вы появились на карте и увидели там своего героя. У вашего героя ограниченное количество ходов: 7.0/7.0
<br>Ходы можно тратить когда угодно. Ходы восстанавливаются постепенно. 100% ходов восстанавливаются за сутки, 50% за 12 часов.

<br>Ваша первая задача: построить деревню в хорошем месте.
(Рядом с вами будут красные сапоги. Не обращайте пока внимания на них.)
===
- Передвижение -

<br>Герой может передвигаться с помощью стрелок, что находятся справа сверху.
<br>Передвижения _на_ разные виды почвы отнимают разное количество ходов.
<br>Передвижение по дороге стоит 0.5 хода
<br>По равнине = 1 ход.
<br>По лесам/деревьям или болотам = 2 хода.
<br>По горам = 3 хода.
<br>По воде герои ходить не могут.
===
- Выбор места для поселения -

<br>Найдите клетку, вокруг которой (на соседних примыкающих клетках) можно найти и горы и лес.
<br>Желательно, чтобы этот город был еще и у моря (не у озер), чтобы из него можно было добраться в любую точку карты на корабле.
<br>Еще лучше, если город будет сам при этом находиться "на горе" или "на деревьях", так как это даст дополнительный бонус при обороне.
<br>(!) Минимальное расстояние между замками в Славии составляет 8 клеток (между замками должно быть 7 клеток незаселенных; на 8й можно селиться).
<br>Справа, в инвентаре вашего героя, есть "Поселенцы". Нажмите на них. Справа появится кнопка "Основать деревню". Жмите.

<br>Ваша деревня будет под защитой новичков, которая называется "Аура тьмы".
<br>За нее автоматически платится "дань" администраторскому аккаунту, сумма которой растет с каждым днем.

<br>Первые здания, которые нужно построить в вашей деревне:
<br>Таверна, Казармы, Рынок
<br>Потом делайте ап-грейд "Центра деревни" до "Цитадели".
<br>Далее развивайте главным образом Фабрику и Дороги.
===
- Размер оброка для ауры тьмы -

<br>1 зол. 
<br>1 зол. 
<br>1 зол. 
<br>3 зол. 
<br>3 зол. 
<br>3 зол. 
<br>4 зол. 1 дер. 
<br>4 зол. 1 дер. 
<br>4 зол. 1 дер. 
<br>5 зол. 3 дер. 
<br>5 зол. 3 дер. 
<br>5 зол. 3 дер. 
<br>15 зол. 7 дер. 5 мет. 
<br>15 зол. 7 дер. 5 мет. 
<br>15 зол. 7 дер. 5 мет. 
<br>25 зол. 12 дер. 12 мет. 
<br>25 зол. 12 дер. 12 мет. 
<br>25 зол. 12 дер. 12 мет. 
<br>35 зол. 16 дер. 16 мет. 
<br>35 зол. 16 дер. 16 мет. 
<br>35 зол. 16 дер. 16 мет.
...
+ 3 дня неуплаты

<br>(*) Ауру тьмы можно снять с себя самостоятельно в разделе "Управление".
<br>(*) В течении первых 2х недель ауру можно принять обратно, через раздел "Управление".
<br>(*) Аура дается только один раз первому поселению игрока. При сносе и отстройке заново аура снова даваться не <br>будет,останется только ускорение работы крестьян.
===
- Как взять/отдать предмет -

<br>Пример: вы должны взять сапоги с клетки на карте (вначале игры).
<br>Для этого достаточно встать на соседнюю с целью клеткой (можно даже на саму клетку с сапогами, но на это <br>израсходуется больше ходов).
<br>Справа от карты, по центру, у вашего героя находится инвентарь. Когда вы будете рядом с объектом, с которым можно будет обменяться вещами (забрать и/или отдать), над инвентарем появятся нужные кнопки "Взять" и "Отдать".
<br>Нажмите на кнопку "Взять" и выберите нужный вам предмет (для ресурсов укажите еще и нужное количество). Жмите "Ок".
<br>Если у вас достаточно места в инвентаре (была свободная клетка для поднятого предмета), вещь должна была появиться у вас в инвентаре.
<br>Теперь нажмите на сапоги. Появятся две кнопки: "Надеть" и "Разрушить". Наденьте сапоги.
<br>Если ваш герой не командует войском, то максимальное количество его ходов должно было увеличиться до 14.
===
- Перерождения на карте -


(*) В игровом мире ведется статистика убийств новичков для оценки агрессивности каждого материка. На материки с высокой смертностью новички будут высаживаться очень редко. Иными словами, каждому новичку подыскивается наиболее свободное и безопасное место. Не обижайте новичков, если не хотите, чтобы земли вокруг вас превратились в пустыню, а враги получали новых бойцов.
(*) Все, кто имеет 1 героя и не имеет замков, могут воспользоваться функцией переноса героя к союзнику или клановцу. Функция доступна в разделе Управление.

Вас выкинуло в плохое место для заселения, или просто далеко от своих?
Вы уже потратили все ходы на сегодня, но вам нужно построить поселение сегодня, а до подходящего места вам еще долго идти?

Решение:
1. Переродиться в случайном месте на карте.
Делается это через раздел "Управление" меню.
После появления в другом месте на карте у вас будет новый герой с полными ходами.

2. Перенестись к союзникам.
===
- Перенос к союзникам -

(Если вам не нужно перемещаться к союзникам, можете пропустить этот пункт)
1. Вступление в клан
В меню слева, в закладке "Клан" подайте заявку.
Дождитесь, когда лидеры клана одобрят Вашу заявку.

2. Перенос
В меню слева найдите закладку "Управление", оно внизу.
В строке "Перенос к союзнику или соклановцу" запишите нужный вам ник и нажмите "Перенос".
Потом нажмите на кнопку сверху справа "В игру".
Вы появитесь в радиусе 5 клеток от столицы вашего союзника. Ходы у вашего героя при этом не обновляются.
===
- Как принять игрока в клан? -	

Откройте закладку "Состав клана", что находится в меню слева.
Вы найдете список всех участников клана, вместе с их званиями.
Имена игроков, подавшие заявки на вступление в клан, будут окрашены в красный цвет.
Справа от них будут две кнопки: "+" (принять в клан/повысить в звании) и "Х" (отклонить заявку/исключить из клана).
Сделайте правильный выбор. Дело сделано.

===
- Как сделать снэпшот? -

Если вы не находитесь на карте, нажмите на кнопку "В игру" справа сверху экрана.
Если вы находитесь на карте, нажмите на портрет вашего героя справа сверху.
Справа появятся кнопки. Среди них будет "Сделать снэпшот". Жмите.

Чтобы просмотреть ваш снимок, нажмите на нижнюю кнопку "Сообщения", чтобы попасть в меню.
В меню слева найдите закладку "Снэпшоты". После нажатия перед вами откроется список ваших снимков.

(*) На снэпшотах не отображается своя скрытая территориальная магия.

Если у игрока, сделавший снимок, еще нет ни одного поселения, его герой не будет отображен на снимке.
(*) Чтобы просмотреть снэпшот вам нужно залогиниться в игру.
===
- Как передать управление (обычным) аккаунтом -

Для того, чтобы вы смогли передать управление вашим аккаунтом кому-либо, у вас должны быть "часы ситтинга".
Они накапливаются сразу после того, как вы сбросите с себя ауру тьмы.
За 1 сутки, за которые вам выдали карму (если был хотя бы 1 заход в игру), накапливаются 3 часа ситтинга.

Теперь откройте меню слева, найдите там внизу закладку "Управление".
Найдите раздел "Передать управление аккаунтом".
Заполните ник (псевдоним) игрокам, кому вы хотите передать управление.
Заполните количество часов, на которое вы хотите ему передать управление.
Поставьте галочки на действия, которые вы ему разрешаете совершать.

Отчет оставшегося времени ситтинга будет начат в момент передачи управления.
Ситтинг также можно отменить, в этом же разделе "Управления".
Важно: во время ситтинга оба игрока могут одновременно управлять юнитами одного аккаунта.
Один игрок не может принимать под свое управление одновременно более 1 аккаунта.
===
Можно передать свой аккаунт под временное управление другому игроку. (см. раздел Управление). 

1. У каждого игрока вводится накопительный счет часов, на которые он может передать свой аккаунт в управление другому игроку. Если хозяин аккаунта заходит в игру, то помимо кармы он будет получать 3 часа к этому счету ежедневно. Максимально можно накопить 900 часов.
2. Управление чужим аккаунтом происходит через свой аккаунт, никакие пароли передавать не нужно.
3. Передать в управление можно не только на сутки, но и на часы. 
4. Аккаунт можно передать в управление только одному игроку. В любой момент хозяин аккаунта может снять управляющего.
5. Одно лицо может управлять только 1 дополнительным аккаунтом. (т.е. 1 человек не может за весь клан играть).
(?) Можно принимать отложенный ситтинг только от 3х игроков в сутки.
===
- Как передать управление аккаунтом -
===
- Miscellaneous (разное) -

(*) Юнит не может ходить от одной клетки к другой, соседствующей с вражескими юнитами.
(*) Банковские переводы доступны после 1 недели игры.
(*) Отпускать можно только одного орка в день!
(*) Войска в деревню можно перекидывать только когда ей будет более 2х недель.
(*) Downtime: 03:15 - 03:30 MCK.
(*) Свою ленту можно создать только начиная с 30го дня игры.
(*) Мертвых героев можно воскресить в таверне любого города (даже вражеского), через 24 часа, за 10 золотых.
(*) Если передвинуть замок, то герои внутри него передвинутся вместе с ним. При этом они потеряют нужное для передвижения количество ходов (если на лес, то (*) 2 хода).
(*) Если вихрь выкинул ваш корабль на берег, и рядом с вами есть клетка воды -- вы можете передвинуться на нее. То есть если это море -- вы можете вернуться обратно в бой.
(*) При попытке атаковать союзника получаем сообщение: "Союзные или клановые соглашения мешают вам атаковать этот объект."
(*) При шагании на клетку с огненной стеной, корабль имеет большой шанс погибнуть.
(*) Юниты находящиеся в транспорте (в кораблях, дирижаблях) не могут атаковать.
(*) Маг, находящийся в транспорте, МОЖЕТ накладывать заклинания.
(*) Если вы уверены, что у врага на море нет свитка рассеивания, то вы можете нейтрализовать корабли врага путем создания изгороди из огненных стен вокруг его корабля (кораблей) или расставив гаргульи. Не забывайте: дальность стрельбы кораблей = 3 клетки (как у лучников).
(*) Внимание! Павшего героя необходимо выкупить в таверне в течение 30 дней, иначе он пропадет.
(*) Для игроков до 3х недель доступен рестарт (с возможностью выбора мира и материка).
(*) В торговых лавках за каждый 4ый уровень добавляется 100 вместимости под ресурсы/войска всем слотам.
(*) У кузницы есть ограничение на максимальное ежедневное количество производств. Это сделано для того, чтобы одна кузница не могла обеспечивать все потребности одного игрока (и тем более не одевала весь клан). Для деревни - 2, города - 4, метрополиса 6 производств в сутки.
(*) Предел уровней зданий: в деревнях - 3, в городах - 13 (кроме кузницы), в метрополисах - 250.
(*) В лесу на темных клетках строить метрополисы нельзя.
(*) Зелье "Лесной дух" показывает в лесу только диких орков (принадлежащих Армии Тьмы). Орки, которые принадлежат другим игрокам, не видны.
(*) Мандрагора станет доступной на продажу в таверне (50 единиц мандрагоры за 400 золотых) когда вам исполнится 2 недели в игре (даже если вы еще под аурой тьмы).
(*) Куст терновика не действует на технику.
(*) Куст терновика ДОБАВЛЯЕТ еще 3 ходов траты при ходе на клетку. Таким образом, стоимость хода на клетску с кустом составляет:
Дорога = 3.5 хода
Равнина = 4 хода
Лес = 5 ходов
Горы = 6 ходов
===
- Скрижаль и руны -

(*) Скрижаль (Rune stone) это место в столице, с помощью которого можно пользоваться рунами. В нем помещаются 3 руны. Вынимать руны можно только 1 раз в сутки.
(*) Замок не сможет менять статус (столица/не столица) чаще раза в неделю.

Виды рун: 
Руна силы - увеличивает силу ближней атаки (+7% за каждый уровень). 
Руна цели - увеличивает силу дальней атаки (+7% за каждый уровень). 
Руна жизни - уменьшает урон, наносимый врагом (-7% за каждый уровень). 
Руна стойкости - увеличивает ближнюю и дальнюю защиту (+7% за каждый уровень). 
Руна времени - уменьшает расход ходов на перемещение по всем типам поверхности 
(-7% за каждый уровень). 
Руна мистицизма - уменьшает затраты маны на заклинания (-7% за каждый уровень).
===
- Грузоподъемность героя -

Грузоподъемность героя:
65535 золота, 25 дерева, 20 металла,10 камня, 500 домовых, 
Древняя пыль 20, Мандрагора 39, Щупальца кракена 40, Кровь орков 50, Папоротник 60. 
Свитков с заклинаниям 1-2 уровня по 25, 3-4 уровня- по 10.
Зелий: (?)
===
- Таблица опыта -

2 уровень = 100 опыта
3 уровень = 200 опыта
4 уровень = 400 опыта
5 уровень = 600 опыта
6 уровень = 1000 опыта
7 уровень = 1600 опыта
8 уровень = 2400 опыта
9 уровень = 3200 опыта
10 уровень = 4800 опыта

(*) После перехода на следующий уровень количество опыта обнуляется.
===
- Обозначения количества войск -

Несколько - до 4х 
Немного - до 8
Группа - до 14 
Отряд - до 25 
Легион - до 45 
Рать - больше 45 солдат
===
- Видимость -

Показатель 15[+2] означает 
15 - это радиус, на котором виден объект остальным. 
+2 это собственные способности по видению других (т.е. если кто-то имеет радиус видимости 3, то с +2 его можно увидеть через 5 клеток). 
===
- Шпионаж -

Каждый лвл шпионажа (столбцы таблицы) 
даёт видимость у количества когорт (строки таблицы) 
________ 1лвл 2лвл 3лвл 4лвл 
1когорта 1 __ 1 __ 1 __ 1 
2когорты 4 __ 3 __ 2 __ 1 
3когорты 7 __ 6 __ 5 __ 4 
4когорты 7 __ 6 __ 5 __ 4 
5когорт  7 __ 6 __ 5 __ 4 
6когорт  7 __ 6 __ 5 __ 4 
7когорт  7 __ 6 __ 5 __ 4 
8когорт  7 __ 6 __ 5 __ 4

(*) Героя с видимостью 1 можно увидеть только вплотную (с соседней клетки).
(*) Стрелков невидимок не видно при стрельбе (враг не видит откуда стреляли, и не знает куда идти чтобы вас найти).
(*) Невидимые герои для ближнего боя видны вражеским стрелкам только вплотную (когда стрелки неэффективны против юнитов ближнего боя).
(!) Заклинание "Суперсенсинг" дает возможность видеть скрытые объекты (в том числе и невидимок).
(*) Герои с навыком шпионажа могут видеть заклинания, висящие на других героях (по shift+клик). Шпионаж 1го уровня позволяет видеть на соседней клетка, 4го уровня - на 4 клетки.
===
--- Религия Диверсий ---

(*) Чтобы переманить орка, вы должны встать на соседнюю с ним клетку леса (героем или техникой). Зажмите кнопку Shift и кликните по орку. В появившемся окне, справа сверху, нажмите на кнопку "Переманить".
(*) Чтобы отказаться от переманенного орка (чтобы отдать его обратно Армии Тьмы) нужно "распустить" этого орка.
(*) Можно переманить орков, вынуть их из темного леса, распустить/сделать их сново дикими, и расстрелять уже спокойно лучниками (не тратя средств на "лесной дух").
(*) Респаун (перерождение орков в понедельник 03:30) не убивает ваших орков (которых вы уже переманили). Они остаются под вашим контролем.
(*) Одновременно можно иметь под своей командой до 3х орков (включительно).
(*) Распускать/отпускать можно максимум одного орка в день.
(*) Орки не передают вещей никому (даже другим оркам). Сообщение при такой попытке: "Орк не захотел ничего отдавать."
(*) Можно разрушать артефакты, которые имеются в инвентаре орка. Это пригодится, например, если враг скоро убьет вашего орка и вы ничего не хотите ему передать из артефактов.
(*) Переманить можно только орков. Драконов/кракенов переманить нельзя (технически невозможно).
(*) Орки, которых вы переманили, не смогут напасть на юнитов, которые принадлежат "Армии Тьмы" (орки/драконы).
(*) Даже если вы надели на голого героя-орка человеческие войска, он все равно не нападет на войска Армии Тьмы.
(*) Голого героя орка можно обучить в своей академии и надеть на него человеческие войска.

- Помощь собрату в любой точке мира -
Один игрок религии диверсий может прийти на помощь другому игроку диверсанту.
Для этого нужно:
1. Первый игрок, которому нужна помощь, переманивает на свою сторону орка и выходит им на арену.
2. Второй игрок, который помогает, выходит на арену и становится рядом с орком игрока-который-просит-помощи.
3. Первый игрок распускает орка/отдает его обратно армии тьмы.
4. Второй игрок переманивает этого орка уже на свою сторону и выходит им через портал арены.
Фокус в том, что появится он обратно на той точке, откуда вышел на арену. Но он уже будет принадлежать другому игроку, который сможет руководить в этой округе еще тремя орками.
(*) Если при этом передать орку поселенцев, он сможет основать поселение. Получаем своего рода телепорт.
(*) Вместе с орком можно передавать и вещи. Получаем обходной способ передачи вещей через арену.
(*) Орки не атакуют других орков вне арены. Орки так же не атакуют драконов (Орк не стал атаковать своих братьев).

- Как экономно убить дракона -	
Дракона можно расстреливать невидимыми для него лучниками (например с видимостью 2). Ответного удара от него быть не последует. Дракона так же можно бить невидимыми мечниками с плетью креспа, через 1 клетку.
===
- Арена -

(*) Если у вас уже есть герой с войками на арене, то новые будут появляться рядом с ним. Но на арене нельзя иметь больше 3х героев одному игроку.
(*) На арене не действуют союзные соглашения, все союзники становятся врагами. Это относится как с союзным кланам, так и к личным союзам. Клановцы остаются клановцами.
(*) При смерти на арене вы теряете всего 10% от убитых войск и не теряете содержимое инвентаря.

(*) Арена: Нельзя уходить с этого острова или атаковать внешние объекты. Пользуйтесь порталами.
(*) На арене невозможно передавать/поднимать с земли вещи. Одевайте своих героев до выхода на арену. Не рвите на арене папоротник: потеряете ход и ничего не получите. Не роняйте ничего на арене, не сможете подобрать обратно.
(*) На портале арены можно стоять героем только если его туда закинуло при попадании на арену. При этом, чтобы выйти с арены через этот портал, нужно сначала убить/убрать героя с клетки с порталом.
(*) На арене невозможно построить поселение.
(*) В темном лесу арены не появляются орки.
(*) На арене не работает "Анонимный режим" религии диверсий. Ваши юниты будут указаны как "???", однако в логах ударов будет указываться ваше реальное имя пользователя.
(*) Герой не может заходить на арену, если на нем висят отрицательные заклинания.
(*) Если, при возвращении с арены, клетка с которой вы попали на арену уже занята, вы появитесь на одной из соседних клеток.
(*) При выходе с арены восстанавливаются HP и мана.
(*) При заходе на арену снимаются все положительные чары с героя (без восстановления).
===
- Орки -

 В лесах обитают разные виды орков:
обычные орки, орки-лучники, элитные орки, орки-шаманы.
Рядом с молодыми игроками появляются более слабые орки, рядом с опытными - сильные.

Орки-шаманы могут вместо атаки использовать магию.
(*) Орки-лучники, которые принадлежат Армии Тьмы, находясь в защите, не стреляют по клеткам с равниной или дорогой, а также по городу (если вы в него зашли).
===
- Драконы -

Каждую неделю в ночь с воскресения на понедельник на некоторые горы прилетают драконы.
Драконы - сильные монстры, справиться с ними в одиночку будет проблематично.
- Драконы селятся на вершинах гор. Рядом с драконом располагаются 4 орка охраны.
- Драконы могут быть от 1 до 10 уровня, от чего зависит их сила и содержимое инвентаря.
- Драконы находятся в обороне, имеют высокое HP.
- У драконов магическая атака по площади - повреждения получает не только юнит, на которого направлена атака, но и соседние юниты в 50% силы).
- Драконы могут использовать магию. Сами к магии не восприимчивы.
- В местах атаки могут вспыхивать огненные стены.
- Из драконов могут выпадать руны и другие ценные вещи

Драконы являются техникой. Это единственная техника, у которой есть уровень.
Примерные данные дракона 9го уровня, находящийся в режиме обороны:
Солдат:     22
Ходы:     5.0 / 5.0
HP:     7600 / 7600
Маг.атака:     15
Защита:     30 д:40
Маг.защита:     30

(*) Во время вашего подхода к дракону он будет произносить заклинания. Чтобы он вам не перегорождал путь, вы можете создать себе "дорожку" из заклинаний "Радуга".
(*) Дракона можно расстреливать невидимыми для него лучниками (например с видимостью 2). Ответного удара от него не поступит. Дракона так же можно бить невидимыми мечниками с помощи плети креспа, через 1 клетку.
===
- Маркеры -

(*) Маркеры ставятся на клетку путем удерживания кнопки Shift и клика мышью на клетку.
(*) Маркер = объявление.
===
- Блок маркер -

Чтобы поставить блок маркер, нужно кликнуть на нужную нам клетку удерживая при этом кнопку Shift. Выбираем тип "Блок маркер" и указываем время действия (5 или 10 минут). 
(*) Каждый игрок может использовать в день максимум 10 минут блок-маркеров.
(*) Каждый игрок может поставить в день 1 маркер на 10 минут или 2 по 5 минут. Этот маркер не дает всем врагам (красным юнитам) двигаться, атаковать, кастовать магию в радиусе 7 клеток и извне внутрь поля. 
(*) Блок маркер можно поставить на любую клетку, кроме клеток с городами и юнитами. 
(*) Блок маркер всегда находится сверху и виден. На него нельзя сходить или повесить магию.
(*) При отмене блок-маркера оставшиеся время не возвращается (даже если оно больше 5 минут).
(*) Состояние своих блок-маркеров можно узнать в разделе "Управление" своего аккаунта.
(*) Нельзя ставить блокирующий маркер на расстоянии ближе 20 клеток к вражеским блокирующим маркерам.
(*) Нельзя поставить маркер, если противник в радиусе 7 клеток делал последний ход или атаку меньше 30 секунд назад (исключение: герои без войск, дирижабли, корабли).
(*) На блок-маркер (даже на свой) нельзя шагнуть героем/техникой (даже воздушной). Будьте осторожны и не ставьте маркеры на своем пути.
(*) В области действия маркера теперь запрещены передачи, ломка артов, начало строительства в обоих мирах.
===
- Как раскачивать героев? -

Если вы атеист, героев нужно раскачивать следующим образом:
1. Мечников/Рыцарей: 4 лидерство, 4 ближний бой, 2 логистика.
2. Лучников/Арбалетчиков: 4 лидерство, 4 стрельба, 2 логистика.
3. Разведчиков: 4 логистика, 4 лидерство, 2 ближний бой.
4. Кнехтов: 4 выносливость, 4 лидерство, 2 ближний бой.
5. Маг-универсал: 3 светлая магия, 3 темная магия, 4 лидерство.
6. Светлый маг: 4 светлая магия, 4 лидерство, 2 логистика.
7. Темный маг: 4 темная магия, 4 лидерство, 2 логистика.
8. Шпион: 4 шпионаж, 3 темная магия (чтобы кастовать "Ослепление" на вражеских лучников), 3 логистика.
===
- Как поднять навыки выше второго уровня - 

Чтобы поднять навык до 3го уровня, герой должен находиться в городе, где есть школа.
Для 4го уровня -- академия. 
Поднимать навыки можно в любом городе: своем, союзном и даже во вражеском.
(!) Чтобы войти в чужой город, герой не должен носить с собой войск (он должен быть "голым").
===
- Скорость доставки товаров (формулы) -

Формулы расчета добычи ресурсов и прибытия войск:
((время добычи или доставки)х8 )/((лвл. фабрики или дороги)+8 ) 
((время призыва)х8 )/((лвл. военнного здания)+7)

Формулы доставки через рынок:

Простых ресурсов: та-же что и доставки добытых ресурсов (24 клетки в сутки изначальная) 
((кол-во клеток)х8 )/((лвл. дороги)+8 ) часов 
пример - 50 клеток, 24лвл дорог = 50х8/(24+8 )=12,5часов.

Войск: (скорость войск в сутки изначальная) 
((кол-во клеток х 24/скорость)х8 )/((лвл. дороги)+8 ) часов 
пример - 50 клеток, 24лвл дорог, мечники = (50х24х8/7)/(24+8 )=42,85часов.
===
- Зелья -

(*) У героя есть 3 места под положительные и 2 под отрицательные заклинания.
(*) Внимание! Если у вас приготовилось зелье, его необходимо вынуть из котла до следующей варки.

Наборы для варки зелий:
Альфа зелья (нужно положить в котел 4 из 6 ингредиентов): 
1 золотой 1 металл 1 камень 1 папоротник 1 мандрагора 1 кровь орков 

Бета зелья (нужно положить в котел 5 из 7 ингредиентов): 
2 папоротник 2 кровь орков 1 щуп кракен 1 чеш дракона 2 мандрагора 1 древняя пыль 1 домовой

Вероятность получения зелий:
---------------------------
Alpha potions:
Combinations (3 6)

     6!        5x6	
___________ = _____ = 15
4! x (6-4)!	2

Alpha: Шанс варки 4/15 = 0.266 = 26.6%
---------------------------
Beta potions: 
Combinations (5 7)

      7!	6x7
___________ = _______ = 21
5! x (7-5)!	 2

Beta: Шанс варки 5/21 = 0.238 = 23.8%
---------------------------

(!) Учитывая то, что у вас есть 3 попытки для нахождения рецепта, шансы сварить 1 зелье составляет:
Альфа зелья: 79.8%
Бета зелья: 71.4%

(*) Папоротник. Юниты могут обнаружить папоротник во время передвижения (когда встают на клетку, где он растет). Места произрастания папоротника меняются каждую неделю. Герои без войск и летяющие юниты могут с вероятностью 50% не заметить растущий папоротник при заходе на клетку. В лесу вероятность произрастания папоротника в 2 раза выше, на дороге в 2 раза меньше. Чтобы собирать больше папоротника - надо больше путешествовать.
===
- Магия -

(*) Время, которое держится магия на клетке, одинаково для всех видов магии. Средний маг будет кастовать примерно на 1.5 суток, самый сильный маг религии магии на 2.5-3 суток.
(*) Можно накладывать магию поверх той, которая уже стоит на клетке (этого же типа). Время будет складываться, владелец магии меняться не будет.
(*) При атаке у мага используется та магическая атака (светлая или темная), которая больше.

(*) У всех юнитов появляется новый параметр - магическая защита (отдельно для темной и светлой магий). Магическая защита работает так же, как и физическая, она определяет сопротивляемость юнита к заклинаниям и магической атаке. Артефакты и навыки, повышающие физическую защиту, против магической не работают. Для повышения магической защиты существуют свои артефакты.
(*) У магов(юнитов) появляется магическая атака (для темной и светлой магий). Физической атаки у магов нет. Магическая атака определяет как силу собственной атаки мага, так и эффективность его заклинаний.
(*) Базовая атака мага в каждом виде магии = 7 + уровень навыка (поэтому маг с недоученным видом магии будет не очень эффективным).
(*) Как и при обычных физических атаках, на магию влияет как величина магической атаки, так и численность войска магов.
===
- Свитки -

(*) "Паутина" отнимает 50% от остаюшихся ходов героя, а не от его максимального количества ходов.

===
- Ставки -

(*) Ставка может строить некоторые виды техники, используя домовых (необходимые ресурсы должны находиться в инвентаре ставки). Техника появляется сразу в случайной свободной клетке рядом со ставкой с 0 ходов.
(*) «Грузоподъемность» ставки составляет 250 геройских.
(*) Из ставки можно отправлять караваны в города с бонусом дорог.
(*) В ставке есть возможность пользоваться банком.
(*) Инвентарь ставки увеличен на 18 ячеек.
(*) С помощью адресной отправки можно посылать караваны в ставки.

===
- Осада замков -

(*) Здания в замках моложе 14 дней будут рушиться при каждом ударе. 
Правило не распространяется на аккаунты, зарегистрированные менее 2х месяцев назад.
(*) Здания в замках зомбировавшихся аккаунтов будут рушиться при каждом ударе.
(*) Ограничение на размещение героев внутри замков до 14 дней с момента основания: деревня - 1, город - 2, метрополис - 3.
Это ограничение не распространяется на игроков, зарегистрированных в игре меньше месяца.
(*) Ставка может сворачиваться в начальное походное состояние. Для этого нужно очистить инвентарь.
(*) В новых поселениях, построенных менее 3х суток назад, нельзя воскрешать погибших героев. В ставках можно воскрешать героев через сутки после ее установки. 
(*) Нельзя класть войска в хранилище замка, которому менее 14 дней.  Это касается передачи напрямую и передачи через рынок. В этот период можно только покупать войска, которые сам замок произвел. В ставку можно загружать войска сразу же после ее установки.
(*) Цена воскрешения героев в ставке стала такая же, как в таверне - 10 монет. Если указанной суммы нет в ставке, то деньги берутся с банковского счета.
(*) При осаде замка, помимо хранилища, также грабятся лавки и прибывшие караваны игрока, которому принадлежит город. Но процент грабежа несколько снижен.
(*) Если герой отдает войска, то он теряет такой процент ходов, какой эти войска составляют от его максимальной вместимости. Если требуемого количества ходов нет, то герой отдать войска не сможет.
(*) В городах можно включать/выключать режим обороны (обстрела проходящих). По умолчанию он отключен. Включать целесообразно только когда враг на пороге.
(*) Чтобы освободить проход по дороге, если герою некуда идти, но у него есть ходы (или недостаточно ходов), можно потратить 1 ход и выйти на арену на время перемещения. При этом, в радиусе 5 клеток, не должно быть врагов.

(*) Пушка.
1. Обладает достаточно сильной дальней атакой. Дальность стрельбы 4 клетки. Ближней атаки нет.
2. При стрельбе по городу без стен и гарнизона рушит здания при каждом выстреле.
3. Способна видеть города в темных лесах.
===
- Техника -

У Мастерской существует апгрейд - Цех. Уровней у мастерской нет.

В мастерской можно производить:
Шахту, Катапульту, Когг, Дирижабль, Обоз
В цеху можно производить:
Галеон, Пушка, Субмарина, Дозорную башню.

1. Техника после окончания службы не самораспускается, но ходить и атаковать она не может. Распускайте самостоятельно.
Это не затрагивает ту технику, которая не является транспортом и у которой отсутствует инвентарь (пушки и катапульты).
2. Техника, построенная мгновенно, рождается с 0 ходов. Чем дольше она строится крестьянами, тем больше ходов она получает при появлении. 100% ходов накапливается за 24 часа постройки.
3. При выходе из техники ходы у героя обнуляются.

*Дозорная башня*
(*) Для создания нужно построить башнестроитель и на нужной клетке преобразовать его в бащню. Башни имеют достаточно большой HP, сенсинг +2, грузоподъемность в 5 геройских, могут вмещать в себя 1 юнит. Атаки у дозорных башен нет.

*Дирижабль*
1. Дирижабли могут летать над любыми поверхностями, перемещение у них всегда отнимает 1 ход.
2. Дирижабли в Вархаосе летают низко, поэтому они не могут занимать одну клетку в поле с другим юнитом. Войска ближнего боя могут атаковать дирижабли в 25% силы. Но дирижабли не блокируются врагами при передвижении и сами не блокируют.
3. Дирижабли могут везти небольшой груз (2 геройские грузоподъемности) и 1 героя без войск.
===
- Обсерватория -

Смотровую башню/Обсерваторию можно развивать по уровням.
У здания дополнительная возможность - сделать снэпшот (снимок) участка карты раз в сутки.
Максимальное расстояние, на котором можно делать снэпшот = 10 + 3*УровеньЗдания
Если в центре снэпшота есть скрытая магия, то она показывается.
Бонусы:
12 уровень - снэпшот делается увеличенного размера (радиус 10).
24 уровень - скрытая магия становится видна в радиусе 1 клетки от центра.
===
- Кракены -

(*) В морях обитают монстры - кракены. 
Кракен имеет видимость 1. 
Обхватывает корабли, подплывшие к нему (на соседних клетках), не давая уплыть. 
Если кракена не убить за 24 часа, то утаскивает корабль на дно.
(*) Когг и брандер не цепляется кракеном.
===
- Тактика на море -

(*) Опасайтесь вихрей на море. 
(*) Если вы наступили на Вихрь, и в радиусе 5 клеток от вихря есть земля, он вас выкинет на землю.
(*) Если в радиусе 5 клеток вокруг вихря нет земли, он вас оставит на месте и никуда не закинет.
(*) Вихрь просматриваются через артефакт "Подзорная труба". Один взор через трубу отнимает 0.5 хода у игроков религии магии; у всех остальных это отнимает 1 ход.
(*) Бывает полезным иметь на корабле героя с разведчиками (с многими ходами), который бы мог просмотреть нужные клетки на море.
(*) Маг на корабле может произносить заклинания, однако не может атаковать. Используйте это чтобы кастовать вихри, стены огня и кусты терновика (когда нужно).
(*) Куст терновика не действует на технику, а значит и на корабли.
(*) Кусты терновика используют на море, чтобы указать безопасный путь для кораблей. В этих же целях можно использовать и радугу.
(*) Не держите своим корабли собранными в квадрат. Их легко окружить стеной огня или заблокировать гаргульями. В этом случае либо вы тратите 1 заклинание "Рассеивание" чтобы сделать себе проход, либо вынуждены стоять в сторонке пока действие заклинания не закончится. Гаргульи эффективно снимать брандерами.
===
- Дипломатия -

(*) Нейтралы могут заключить мирный договор с кланом. Для этого игроку, не состоящему в клане, нужно зайти на клановую ленту и предложить там мир.
(*) Чтобы заключить мирный договор между кланами: Правитель первого клана должен оставить на ленте второго клана предложение о мирном договоре. Правитель второго клана должен нажать на кнопку "Заключить мирный договор".
==
- Кузница и артефакты -

(*) Рецепты необходимо записать в свободные слоты кузницы или башни магов, чтобы город получил возможность производить соответствующие изделия. Все рецепты рассчитаны на определенное число изготовлений предмета. При извлечении записанного рецепта из кузницы/башни оставшееся кол-во изготовлений сокращается в 2 раза. Рецепты выпадают из монстров.
(*) В кузнице/башнях в городах 2 слота, в метрополисах - 3.
(*) Если герой надевает артефакт, то рядом с названием артефакта появляется * (звездочка). Если такой артефакт передать, то его жизнь сократится на 4 дня. Это штраф за передачу артефакта, который уже использовался данным героем. После передачи звездочка пропадает.
(*) Примечание: Даже если у артефакта после передачи осталось 0 дней жизни, разрушится он только в 03:15 МСК
(*) При снятии артефакта сохраняется % ходов.
(*) При взятии голым героем войск/выкладывании всех войск сохраняется % ходов.